# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
# theme: jekyll-theme-minimal


title: Hongying's homepage
description: Bookmark this to keep an eye on my project updates!
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman