# title: Hongying's homepage # this setting seems not working
# description: Bookmark this to keep an eye on my project updates!
# show_downloads: false
# google_analytics:
# # theme: jekyll-theme-cayman
# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

title: Hongying Yue
logo: /assets/img/headshot_circle.JPG
#description: text below image
show_downloads: false
theme: jekyll-theme-minimal